### ISSUE TITLE
Lots of console Warnings making it unusable due to performance

### ISSUE THREAD

**Issue by goto3** [tiavina-mika/mui-tiptap-editor#73]
### Describe the bug

I am getting 9 warnings to the console each character I type in the text field, they are all the same:

```
[tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead. Found in extension: "node". Error Component Stack
    at TextEditor (TextEditor.js:80:23)
    at div (<anonymous>)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (Grid.js:387:89)
    at div (<anonymous>)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (Grid.js:387:89)
    at Step3 (step-3.tsx:22:25)
    at div (<anonymous>)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (createStack.js:160:24)
    at div (<anonymous>)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (createStack.js:160:24)
    at div (<anonymous>)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at CardContent (CardContent.js:52:84)
    at form (<anonymous>)
    at div (<anonymous>)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at Paper (Paper.js:87:85)
    at eval (emotion-element-43c6fea0.browser.esm.js:60:66)
    at Card (Card.js:53:84)
```

this makes the performance very poor even in my AMD 7800X3D.

1. Material UI (v5) installed.

### To Reproduce

1. Use the stock example from the main page

### Expected behavior

No warnings in the console

### Screenshots

![image](https://github.com/user-attachments/assets/e4a7d6a0-2e22-4cd9-9c3a-2354a2d5b032)

![image](https://github.com/user-attachments/assets/29b321ee-b57a-4b8e-be79-fad9c0766615)

### System (please complete the following information)

- mui-tiptap-editor version: latest
- tiptap version: latest
- Browser: Chrome, latest
- Node version: 20
- OS: Windows

```tsx

export function Step3({ formik }: Props): React.JSX.Element {  
  const [value, setValue] = React.useState('');  

  const handleChange = (newValue: string) => setValue(newValue);

  return (<>
    <Grid container spacing={3} sx={{ display: 'flex', justifyContent: 'left' }}>
      <Grid item sm={12} xs={12}>
        <TextEditor value={value} onChange={handleChange} />
      </Grid>
    </Grid>
  </>)
}

```

**Comment by akreienbring** [comment]
True! The thing is mentioned here: https://github.com/taiga-family/taiga-ui/issues/1290 but as far as I can see, there's no solution provided. 

Did you find one?

**Comment by tiavina-mika** [comment]
Fixed in this [PR](https://github.com/tiavina-mika/mui-tiptap-editor/pull/74/files). Please update to `mui-tiptap-editor@latest`

**Comment by tiavina-mika** [comment]
Fixed in this [PR](https://github.com/tiavina-mika/mui-tiptap-editor/pull/74/files). Please update to `mui-tiptap-editor@latest`
